# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20190522_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
